travis:
  secure:
    BINSTAR_TOKEN: cqQDQ3ERT9nauwqy9lU2Mq3K8drFpqEOOteSYr9sIVRRa7ly0aFPR5lCfsLtCzxKg7p7ZVuiH9AyVM+6P1bM0DjdY1LVfMZW0u1yPE74SKaG4OyNXJEttJbua5XjikymoezOEFvsDWzMctTnFPGzXIOH5p5bO/4yY5G6P5nLEGEvR9HPnHtayElkUUbyDiUNCUtooHHabN3smlrxmiaGIaURVp79fN9jFgfcVOE6LbZWO8xLXM58BI0kUpPjgCdDYwgZ13+sQESJoJjBkc5iZGH3pODswN34pJmnSXtD3eEYVdI56p2D/mdtv7Xyv8Oov2864LuHf5DCkmlZRy6iGTy6An9ScZDouyyH3mJbcEC2yj2Ti6c9bycSMWTZceewIUNajTpn6a279yzsyed+VYT1H65N3WniTwJFTWoZGlK4zrQJLOqWiOWWjizysqCnaqD9OXcH0fuM0lGzyPLfJYLFfPke2gsgYrw4ewQdX2i909CqC0a9kJsK1vT+wADds6jk0pBKIkEb/paHMabZKezBgc+RoXORrt+lprXHdWKDHwTijyMAfGaqPd5VgC+fh8e71D5xZi2CKScGupZkgVlO0MUM06n8P4MWmOaGNxulhj5Bn1PSwnVjf52FJED7Mlo6iInIEL+fZ84I5aoDg3AxvUM61AgKSOvJNiPqWAg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
